package com.myspace.bedqd;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataMonitoringObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "dmPriorStartDate")
	private java.util.Date dmPriorStartDate;
	@org.kie.api.definition.type.Label(value = "dmPriorEndDate")
	private java.util.Date dmPriorEndDate;
	@org.kie.api.definition.type.Label(value = "dmCurrentStartDate")
	private java.util.Date dmCurrentStartDate;
	@org.kie.api.definition.type.Label(value = "dmCurrentEndDate")
	private java.util.Date dmCurrentEndDate;
	@org.kie.api.definition.type.Label(value = "dmRuleName")
	private java.lang.String dmRuleName;

	public DataMonitoringObject() {
	}

	public java.util.Date getDmPriorStartDate() {
		return this.dmPriorStartDate;
	}

	public void setDmPriorStartDate(java.util.Date dmPriorStartDate) {
		this.dmPriorStartDate = dmPriorStartDate;
	}

	public java.util.Date getDmPriorEndDate() {
		return this.dmPriorEndDate;
	}

	public void setDmPriorEndDate(java.util.Date dmPriorEndDate) {
		this.dmPriorEndDate = dmPriorEndDate;
	}

	public java.util.Date getDmCurrentStartDate() {
		return this.dmCurrentStartDate;
	}

	public void setDmCurrentStartDate(java.util.Date dmCurrentStartDate) {
		this.dmCurrentStartDate = dmCurrentStartDate;
	}

	public java.util.Date getDmCurrentEndDate() {
		return this.dmCurrentEndDate;
	}

	public void setDmCurrentEndDate(java.util.Date dmCurrentEndDate) {
		this.dmCurrentEndDate = dmCurrentEndDate;
	}

	public java.lang.String getDmRuleName() {
		return this.dmRuleName;
	}

	public void setDmRuleName(java.lang.String dmRuleName) {
		this.dmRuleName = dmRuleName;
	}

	public DataMonitoringObject(java.util.Date dmPriorStartDate,
			java.util.Date dmPriorEndDate, java.util.Date dmCurrentStartDate,
			java.util.Date dmCurrentEndDate, java.lang.String dmRuleName) {
		this.dmPriorStartDate = dmPriorStartDate;
		this.dmPriorEndDate = dmPriorEndDate;
		this.dmCurrentStartDate = dmCurrentStartDate;
		this.dmCurrentEndDate = dmCurrentEndDate;
		this.dmRuleName = dmRuleName;
	}

}