package com.myspace.bedqd;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InternalControlObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "icStartDate")
	private java.util.Date icStartDate;
	@org.kie.api.definition.type.Label(value = "icEndDate")
	private java.util.Date icEndDate;
	@org.kie.api.definition.type.Label(value = "internalRuleName")
	private java.lang.String internalRuleName;

	public InternalControlObject() {
	}

	public java.util.Date getIcStartDate() {
		return this.icStartDate;
	}

	public void setIcStartDate(java.util.Date icStartDate) {
		this.icStartDate = icStartDate;
	}

	public java.util.Date getIcEndDate() {
		return this.icEndDate;
	}

	public void setIcEndDate(java.util.Date icEndDate) {
		this.icEndDate = icEndDate;
	}

	public java.lang.String getInternalRuleName() {
		return this.internalRuleName;
	}

	public void setInternalRuleName(java.lang.String internalRuleName) {
		this.internalRuleName = internalRuleName;
	}

	public InternalControlObject(java.util.Date icStartDate,
			java.util.Date icEndDate, java.lang.String internalRuleName) {
		this.icStartDate = icStartDate;
		this.icEndDate = icEndDate;
		this.internalRuleName = internalRuleName;
	}

}