package com.myspace.bedqd;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KeyHighlightsObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "khPriorStartDate")
	private java.util.Date khPriorStartDate;
	@org.kie.api.definition.type.Label(value = "khPriorEndDate")
	private java.util.Date khPriorEndDate;
	@org.kie.api.definition.type.Label(value = "khCurrentStartDate")
	private java.util.Date khCurrentStartDate;
	@org.kie.api.definition.type.Label(value = "khCurrentEndDate")
	private java.util.Date khCurrentEndDate;
	@org.kie.api.definition.type.Label(value = "khRuleName")
	private java.lang.String khRuleName;

	public KeyHighlightsObject() {
	}

	public java.util.Date getKhPriorStartDate() {
		return this.khPriorStartDate;
	}

	public void setKhPriorStartDate(java.util.Date khPriorStartDate) {
		this.khPriorStartDate = khPriorStartDate;
	}

	public java.util.Date getKhPriorEndDate() {
		return this.khPriorEndDate;
	}

	public void setKhPriorEndDate(java.util.Date khPriorEndDate) {
		this.khPriorEndDate = khPriorEndDate;
	}

	public java.util.Date getKhCurrentStartDate() {
		return this.khCurrentStartDate;
	}

	public void setKhCurrentStartDate(java.util.Date khCurrentStartDate) {
		this.khCurrentStartDate = khCurrentStartDate;
	}

	public java.util.Date getKhCurrentEndDate() {
		return this.khCurrentEndDate;
	}

	public void setKhCurrentEndDate(java.util.Date khCurrentEndDate) {
		this.khCurrentEndDate = khCurrentEndDate;
	}

	public java.lang.String getKhRuleName() {
		return this.khRuleName;
	}

	public void setKhRuleName(java.lang.String khRuleName) {
		this.khRuleName = khRuleName;
	}

	public KeyHighlightsObject(java.util.Date khPriorStartDate,
			java.util.Date khPriorEndDate, java.util.Date khCurrentStartDate,
			java.util.Date khCurrentEndDate, java.lang.String khRuleName) {
		this.khPriorStartDate = khPriorStartDate;
		this.khPriorEndDate = khPriorEndDate;
		this.khCurrentStartDate = khCurrentStartDate;
		this.khCurrentEndDate = khCurrentEndDate;
		this.khRuleName = khRuleName;
	}

}